language: ruby
sudo: required
rvm: 2.4
addons:
  chrome: stable
script:
  - chromedriver-update 2.36
  - chromedriver --version
  - bundle exec jekyll build
  - bundle exec rake wax:test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
